language: ruby
cache:
  apt: true
  directories:
    - vendor/bundle
    - $HOME/.cache/pip
rvm:
  - 2.3
  - 2.4
  - 2.5
  - jruby
  - truffleruby
before_install:
  - type bundle || gem install bundler --version '~> 1.0'
install:
  - bundle install --path vendor/bundle --jobs=3 --retry=3
